<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Product_model extends CI_Model
{

    public $table = 'product';
    public $id = 'product_ID';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('product_image,product_ID,product_name,product_category,product_price,product_description,product_time_duration,product_dimensions,product_weight,popular');
        $this->datatables->from('product');
        //add this line for join
        //$this->datatables->join('table2', 'product.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('product/read/$1'),'
            <button type="button" class="btn btn-primary">
                <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
            </button>')."".anchor(site_url('product/update/$1'),'
            <button type="button" class="btn btn-success">
                <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
            </button>')."".anchor(site_url('product/delete/$1'),'
            <button type="button" class="btn btn-danger">
                <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
            </button>','onclick="javasciprt: return confirm(\'Anda yakin ingin menghapus data ini ?\')"'), 'product_ID');
        return $this->datatables->generate();
    }

    function get_by_view(){
        $this->db->order_by('product_count_view', $this->order);
        return $this->db->get($this->table)->result();
    }

    function get_by_category($category){
        $this->db->where('product_category', $category);
        return $this->db->get($this->table)->result();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('product_ID', $q);
        $this->db->or_like('product_name', $q);
        $this->db->or_like('product_category', $q);
        $this->db->or_like('product_price', $q);
        $this->db->or_like('product_image', $q);
        $this->db->or_like('product_description', $q);
        $this->db->or_like('product_time_duration', $q);
        $this->db->or_like('product_count_view', $q);
        $this->db->or_like('product_dimensions', $q);
        $this->db->or_like('product_weight', $q);
        $this->db->from($this->table);
        //$this->db->'nama' => set_value('nama'),
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('product_ID', $q);
        $this->db->or_like('product_name', $q);
        $this->db->or_like('product_category', $q);
        $this->db->or_like('product_price', $q);
        $this->db->or_like('product_image', $q);
        $this->db->or_like('product_description', $q);
        $this->db->or_like('product_time_duration', $q);
        $this->db->or_like('product_count_view', $q);
        $this->db->or_like('product_dimensions', $q);
        $this->db->or_like('product_weight', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    function update_view($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
        return $this->db->get($this->table)->row();
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Product_model.php */
/* Location: ./application/models/Product_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-09-04 22:47:29 */
/* http://harviacode.com */
