<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Transaction_model extends CI_Model
{

    public $table = 'transaction';
    public $id = 'transaction_ID';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('transaction_ID,transaction_status,transaction_time,user_ID,destination_address,information');
        $this->datatables->from('transaction');
        //add this line for join
        //$this->datatables->join('table2', 'transaction.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('transaction/read/$1'),'
            <button type="button" class="btn btn-primary">
                <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
            </button>')."".anchor(site_url('transaction/update/$1'),'
            <button type="button" class="btn btn-success">
                <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
            </button>')."".anchor(site_url('transaction/delete/$1'),'
            <button type="button" class="btn btn-danger">
                <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
            </button>','onclick="javasciprt: return confirm(\'Anda yakin ingin menghapus data ini ?\')"'), 'transaction_ID');
        return $this->datatables->generate();
    }


    // get all
     function get_all_by_type()
    {
        $this->db->order_by("transaction_status", $this->order);
        return $this->db->get($this->table)->result();
    }
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('transaction_ID', $q);
    	$this->db->or_like('transaction_status', $q);
    	$this->db->or_like('transaction_time', $q);
    	$this->db->or_like('user_ID', $q);
        $this->db->or_like('transaction_image', $q);
    	$this->db->or_like('destination_address', $q);
    	$this->db->or_like('information', $q);

    	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('transaction_ID', $q);
    	$this->db->or_like('transaction_status', $q);
    	$this->db->or_like('transaction_time', $q);
    	$this->db->or_like('user_ID', $q);
        $this->db->or_like('transaction_image', $q);
    	$this->db->or_like('destination_address', $q);
    	$this->db->or_like('information', $q);
       
    	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
        return $this->db->insert_id();
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Transaction_model.php */
/* Location: ./application/models/Transaction_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-09-04 22:47:36 */
/* http://harviacode.com */